### ISSUE TITLE
add isEmpty() function to stdlib? 

### ISSUE THREAD

**Issue by burdettadam** [Picolab/node-krl-stdlib#5]
the old kre has isNull(). I would like the ability to check if a map is empty, or a string is blank, or an array is empty.

**Comment by windley** [comment]
In general, because KRL is a truthy language, you can just do

a = “”;
b = a => “true” | “false”;

b will have the value false. 

a.isNull() would be false and is use to distinguish “empty” from “null”.

**Comment by 0joshuaolson1** [comment]
Copied to https://github.com/Picolab/pico-engine/issues/310
